# from https://sourceforge.net/p/snowmix/wiki/Snowmix%20Tutorials%20-%20Scenes/

# Specify that Snowmix version major number must be 4 and and least minor number 4
require version 0.4.4

# Listen on port 9999 for command control connections
system control port 9999

# Set system Geometry to WIDTH HEIGHT
system geometry 1280 720 ARGB

# Set system frame rate to N or NN.NN
system frame rate 24

# Set output control socket
system socket /tmp/mixer1

# Change default settings for maxplaces BEFORE any of the shape, text etc. commands
maxplaces shapes 90
maxplaces shapes 170
maxplaces shapeplaces 64
maxplaces shapeplaces 128
maxplaces strings 180
maxplaces texts 180
maxplaces loaded_images 16
maxplaces placed_images 16
maxplaces video_feeds 16
maxplaces audio_feeds 20
maxplaces audio_mixers 20
maxplaces audio_sink 20
# PreShow and Show must end with a loop statement
command create PreShow
  loop
command end
overlay pre PreShow
command create Show
  loop
command end
overlay finish Show

# Load libraries
include ../slib/system.slib
include ../slib/scenes.slib
include ../slib/feeds.slib
include ../slib/images.slib
include ../slib/basic-shapes.slib
include ../slib/clocks2.slib
include ../slib/texts.slib
message Snowmix Libraries Loaded in minimal init